#!/usr/bin/env python3
"""
gen_undo_core_test.py - generates tools/undo_core_test.c by extracting the
Undo engine verbatim (byte-for-byte, from the CP932 source) out of
TSUBAKI.C, and wrapping it in a small native (host) C test harness.

This exists so the unit test always exercises the exact code that ships in
TSUBAKI.C, rather than a hand-retyped copy that could silently drift from
it - same rationale and technique as gen_search_core_test.py.

Extracted verbatim, in file order (one contiguous block in TSUBAKI.C, from
is_lead_byte() through the end of undo_perform() - handle_undo_key() itself
is deliberately NOT extracted, since it only dispatches ^U/^Z to
undo_perform() and formats a status-line notice via sappend_copy()/MSG(),
neither of which exists in this host harness):
  is_lead_byte, rebuild_lines, line_len, char_len_at, prev_char_start,
  col_at_byte, byte_at_col, clamp_cursor, ensure_visible, undo_evict_for,
  undo_push, buffer_insert, buffer_delete, locate_offset, undo_perform.

The #defines and globals these functions need (TEXT_MAX, MAX_LINES,
TAB_WIDTH, VRAM_COLS, BODY_ROWS, the UNDO_* constants, g_text[], etc.) are
also pulled out of TSUBAKI.C by name, so their values can't silently drift
from the shipped source either.

Run:
  python3 tools/gen_undo_core_test.py
  cc -std=c89 -Wall -o /tmp/undo_core_test tools/undo_core_test.c
  /tmp/undo_core_test

TSUBAKI.C is CP932-encoded; this script reads it as bytes and only decodes
to text to locate the function/define/global boundaries, exactly like
check.py and gen_search_core_test.py do.
"""
import os
import re
import sys


def extract_block(text, start_marker, end_marker):
    i = text.index(start_marker)
    j = text.index(end_marker, i)
    return text[i:j].rstrip("\n") + "\n"


def _drop_trailing_comment(line):
    """cuts a source line at its first '/*', dropping any trailing comment.
    Several of TSUBAKI.C's #define/global-declaration comments continue
    onto a following line (e.g. UNDO_RESULT_FAILED's), which a same-line-
    only capture would leave unterminated in the generated file - so
    trailing comments are simply dropped rather than reproduced here."""
    return line.split("/*", 1)[0].rstrip()


def extract_define_line(text, name):
    m = re.search(r"^#define\s+" + re.escape(name) + r"\s+.*$", text, re.M)
    if m is None:
        raise SystemExit("could not find #define %s in TSUBAKI.C" % name)
    return _drop_trailing_comment(m.group(0))


def extract_global_decl(text, name):
    m = re.search(r"^(?:unsigned\s+char|unsigned\s+int|int|char)\s+" +
                   re.escape(name) + r"(?:\[[^\]]*\])?\s*;.*$", text, re.M)
    if m is None:
        raise SystemExit("could not find global declaration of %s in TSUBAKI.C" % name)
    return _drop_trailing_comment(m.group(0))


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src_path = os.path.join(here, "..", "TSUBAKI.C")
    with open(src_path, "rb") as f:
        data = f.read()
    text = data.decode("cp932")

    defines = [extract_define_line(text, n) for n in (
        "TEXT_MAX", "MAX_LINES", "TAB_WIDTH", "VRAM_COLS", "BODY_ROWS",
        "UNDO_BUF_SIZE", "UNDO_MASK", "UNDO_TYPE_INSERT", "UNDO_TYPE_DELETE",
        "UNDO_HDR_SIZE", "UNDO_FOOTER_SIZE", "UNDO_RESULT_EMPTY",
        "UNDO_RESULT_OK", "UNDO_RESULT_FAILED",
    )]

    globals_ = [extract_global_decl(text, n) for n in (
        "g_text", "g_lineStart", "g_textLen", "g_lineCount",
        "g_curLine", "g_curByte", "g_goalCol", "g_topLine", "g_leftCol",
        "g_lineOverflow", "g_modified",
        "g_undoBuf", "g_undoWrite", "g_undoUsed", "g_undoApplying", "g_undoTmp",
    )]

    engine_src = extract_block(
        text,
        "int is_lead_byte(unsigned char c)",
        "\n\n/* ^U / ^Z をUndoに割り当てる。")

    out_path = os.path.join(here, "undo_core_test.c")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("""/*
 * undo_core_test.c - GENERATED by gen_undo_core_test.py. Do not edit by
 * hand; re-run the generator instead.
 *
 * Host-native (not SmallerC/PC-98) unit test for TSUBAKI.C's Undo engine.
 * is_lead_byte() through undo_perform() below are extracted verbatim from
 * TSUBAKI.C (see gen_undo_core_test.py for the exact function list), so
 * this test exercises the exact code that ships, not a hand-retyped copy.
 */
#include <stdio.h>
#include <string.h>

/* ---- constants extracted from TSUBAKI.C's #defines ------------------ */
""")
        for d in defines:
            f.write(d + "\n")
        f.write("""
/* ---- globals extracted from TSUBAKI.C's declarations ----------------- */
""")
        for g in globals_:
            f.write(g + "\n")
        f.write("""
/* ---- Undo engine, extracted verbatim from TSUBAKI.C ------------------ */

""")
        f.write(engine_src)
        f.write("""
/* ---- test harness ------------------------------------------------- */

static void reset_state(void)
{
    g_textLen = 0;
    g_text[0] = 0;
    rebuild_lines();
    g_curLine = 0;
    g_curByte = 0;
    g_goalCol = 0;
    g_topLine = 0;
    g_leftCol = 0;
    g_lineOverflow = 0;
    g_modified = 0;
    g_undoWrite = 0;
    g_undoUsed = 0;
    g_undoApplying = 0;
}

static int failures = 0;

static void check(int cond, const char *label)
{
    printf("%-70s %s\\n", label, cond ? "PASS" : "FAIL");
    if (!cond) failures++;
}

/* ---- case 1: insert, then undo restores the original text ------------ */
static void test_insert_then_undo(void)
{
    int ok;

    reset_state();
    strcpy(g_text, "abcdef");
    g_textLen = (int)strlen(g_text);
    rebuild_lines();

    ok = buffer_insert(3, "XYZ", 3, 0);
    check(ok, "insert: buffer_insert() succeeds");
    check(strcmp(g_text, "abcXYZdef") == 0, "insert: text after insert is 'abcXYZdef'");
    check(g_undoUsed > 0, "insert: undo log is non-empty after insert");

    ok = (undo_perform() == UNDO_RESULT_OK);
    check(ok, "insert: undo_perform() reports OK");
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "abcdef") == 0, "insert: undo restores 'abcdef'");
    check(g_undoUsed == 0, "insert: undo log is empty again after the single undo");
}

/* ---- case 2: delete (incl. a 2-byte SJIS char), then undo restores the
   deleted bytes exactly -------------------------------------------------- */
static void test_delete_then_undo_sjis(void)
{
    int ok;
    /* "a" + KANJI U+6F22 as SJIS (0x8A 0xBF, "漢") + "b" */
    char before[8];
    int beforeLen;

    reset_state();
    before[0] = 'a'; before[1] = (char)0x8A; before[2] = (char)0xBF; before[3] = 'b'; before[4] = 0;
    beforeLen = 4;
    memcpy(g_text, before, (size_t)beforeLen + 1);
    g_textLen = beforeLen;
    rebuild_lines();

    /* delete the 2-byte SJIS character at offset 1 */
    buffer_delete(1, 2);
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "ab") == 0, "delete(sjis): text after delete is 'ab'");
    check(g_undoUsed > 0, "delete(sjis): undo log is non-empty after delete");

    ok = (undo_perform() == UNDO_RESULT_OK);
    check(ok, "delete(sjis): undo_perform() reports OK");
    g_text[g_textLen] = 0;
    check(g_textLen == beforeLen && memcmp(g_text, before, (size_t)beforeLen) == 0,
          "delete(sjis): undo restores the exact deleted SJIS bytes");
}

/* ---- case 3: several edits, undo unwinds them in reverse order -------- */
static void test_multiple_edits_reverse_order(void)
{
    reset_state();
    strcpy(g_text, "");
    g_textLen = 0;
    rebuild_lines();

    buffer_insert(0, "AAA", 3, 0);   /* "AAA" */
    buffer_insert(3, "BBB", 3, 0);   /* "AAABBB" */
    buffer_delete(0, 1);             /* "AABBB" (deleted the first 'A') */

    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AABBB") == 0, "multi: state after 3 edits is 'AABBB'");

    undo_perform(); /* undoes the delete: restore the leading 'A' */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AAABBB") == 0, "multi: undo #1 (of delete) -> 'AAABBB'");

    undo_perform(); /* undoes the second insert ("BBB") */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AAA") == 0, "multi: undo #2 (of insert BBB) -> 'AAA'");

    undo_perform(); /* undoes the first insert ("AAA") */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "") == 0, "multi: undo #3 (of insert AAA) -> ''");

    check(undo_perform() == UNDO_RESULT_EMPTY, "multi: undo #4 reports EMPTY (nothing left)");
}

/* ---- case 4: ring overflow evicts the oldest record, which then can no
   longer be undone --------------------------------------------------- */
static void test_ring_overflow_evicts_oldest(void)
{
    int i;
    int totalPushes;
    char chunk[64];
    int chunkLen;
    int recBytes;
    int capacity;

    reset_state();
    g_textLen = 0;
    g_text[0] = 0;
    rebuild_lines();

    /* Each insert of chunkLen bytes costs UNDO_HDR_SIZE+UNDO_FOOTER_SIZE
       bytes of ring space (inserts don't carry a payload). Push enough
       distinct, individually-labelled inserts to overflow UNDO_BUF_SIZE
       several times over, so the oldest ones are guaranteed evicted. */
    chunkLen = 8;
    recBytes = UNDO_HDR_SIZE + UNDO_FOOTER_SIZE;
    capacity = UNDO_BUF_SIZE / recBytes;
    totalPushes = capacity * 3; /* push 3x the ring's record capacity */

    for (i = 0; i < totalPushes; i++) {
        sprintf(chunk, "%07d;", i); /* exactly 8 bytes: 7 digits + ';' */
        buffer_insert(g_textLen, chunk, chunkLen, 0);
    }

    check(g_undoUsed <= UNDO_BUF_SIZE, "overflow: undo log never exceeds UNDO_BUF_SIZE");

    /* Each buffer_insert() appended its chunk at the then-current
       g_textLen, so g_text is chunk0+chunk1+...+chunk(totalPushes-1) in
       order. Undo pops the most-recently-pushed record first (LIFO), so
       undoing repeatedly removes chunks from the END of g_text, working
       back toward chunk0. Keep undoing until the log reports EMPTY. */
    {
        int undoneCount = 0;
        int r;
        while ((r = undo_perform()) == UNDO_RESULT_OK) {
            undoneCount++;
            if (undoneCount > totalPushes) break; /* safety valve */
        }
        check(r == UNDO_RESULT_EMPTY, "overflow: eventually reports EMPTY (ring is finite)");
        check(undoneCount > 0 && undoneCount < totalPushes,
              "overflow: undid some records, but fewer than were pushed");
        printf("    (pushed %d records of %d bytes each; ring held room for "
               "~%d; %d were actually undoable)\\n",
               totalPushes, chunkLen, capacity, undoneCount);

        /* The decisive check: chunk #0 (the OLDEST edit) must still be
           sitting at the very start of g_text, unremoved - proving its
           undo record was the one discarded when the ring overflowed,
           exactly as the ring-buffer eviction policy requires (oldest
           record evicted first, not some arbitrary one). If eviction were
           broken (e.g. evicting from the wrong end, or not evicting at
           all and instead corrupting the ring), this specific assertion
           would fail even if the generic checks above happened to pass. */
        check(g_textLen >= chunkLen &&
              memcmp(g_text, "0000000;", (size_t)chunkLen) == 0,
              "overflow: chunk #0 (oldest push) remains un-undoable in g_text");
    }
}

int main(void)
{
    printf("%-70s %s\\n", "case", "result");
    test_insert_then_undo();
    test_delete_then_undo_sjis();
    test_multiple_edits_reverse_order();
    test_ring_overflow_evicts_oldest();

    if (failures == 0) {
        printf("\\nALL CASES PASSED\\n");
        return 0;
    } else {
        printf("\\n%d CASE(S) FAILED\\n", failures);
        return 1;
    }
}
""")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
