/*
 * search_core_test.c - GENERATED by gen_search_core_test.py. Do not edit by
 * hand; re-run the generator instead.
 *
 * Host-native (not SmallerC/PC-98) unit test for TSUBAKI.C's search
 * matching core. is_lead_byte() and line_find() below are extracted
 * verbatim from TSUBAKI.C so this test exercises the exact code that
 * ships, not a hand-retyped copy. See docs/tsubaki-spec-01.md 9 and
 * docs/editor-measure-04.md for the design/measurement this checks
 * against.
 */
#include <stdio.h>
#include <string.h>

int is_lead_byte(unsigned char c)
{
  return (c >= 0x81 && c <= 0x9F) || (c >= 0xE0 && c <= 0xFC);
}

int line_find(char *hay, int hayLen, int startByte, char *term, int termLen)
{
  int i;
  int chLen;
  unsigned char c;

  if (termLen <= 0) return -1;

  i = startByte;
  while (i + termLen <= hayLen) {
    if (memcmp(hay + i, term, (unsigned)termLen) == 0) return i;
    c = (unsigned char)hay[i];
    chLen = (is_lead_byte(c) && i + 1 < hayLen) ? 2 : 1;
    i += chLen;
  }
  return -1;
}

/* ---- test harness ------------------------------------------------- */

struct TestCase {
    const char *haystackCp932; /* CP932 bytes, C string literal (no embedded NUL) */
    const char *termCp932;
    int expectFound;   /* 1 = expect a match, 0 = expect no match */
    int expectPos;     /* byte offset expected when expectFound == 1 */
    const char *label;
};

static struct TestCase g_cases[] = {
    { "\x8b\x41\x82\xe9\x93\xb9", "A", 0, 0,
      "\xe5\xb8\xb0\xe3\x82\x8b\xe9\x81\x93(帰る道) find 'A'" },
    { "\x8b\x61\x82\xc6\x83\x41\x83\x8a", "A", 0, 0,
      "\xe8\x9f\xbb\xe3\x81\xa8\xe3\x82\xa2\xe3\x83\xaa(蟻とアリ) find 'A'" },
    { "\x8b\x61\x82\xc6\x83\x41\x83\x8a", "a", 0, 0,
      "(蟻とアリ) find 'a'" },
    { "A alone", "A", 1, 0,
      "'A alone' find 'A'" },
    { "FIND me here", "find", 0, 0,
      "'FIND me here' find 'find' (case-sensitive)" },
    { "\x8a\xbf\x8e\x9a\x82\xcc\x83\x65\x83\x58\x83\x67", "\x8a\xbf\x8e\x9a", 1, 0,
      "(漢字のテスト) find (漢字)" },
    { "\x8b\x41\x82\xe9\x93\xb9", "\x82\xe9", 1, 2,
      "(帰る道) find (る)" },
    { NULL, NULL, 0, 0, NULL }
};

int main(void)
{
    int i;
    int failures;
    int hayLen;
    int termLen;
    int pos;
    int ok;

    failures = 0;

    printf("%-46s %-8s %-10s %-8s %s\n", "haystack/term (label)", "expect", "got", "pos", "result");
    for (i = 0; g_cases[i].haystackCp932 != NULL; i++) {
        hayLen = (int)strlen(g_cases[i].haystackCp932);
        termLen = (int)strlen(g_cases[i].termCp932);
        pos = line_find((char *)g_cases[i].haystackCp932, hayLen, 0,
                         (char *)g_cases[i].termCp932, termLen);

        if (g_cases[i].expectFound) {
            ok = (pos == g_cases[i].expectPos);
        } else {
            ok = (pos == -1);
        }
        if (!ok) failures++;

        printf("%-46s %-8s %-10d %-8d %s\n",
               g_cases[i].label,
               g_cases[i].expectFound ? "match" : "no match",
               pos,
               g_cases[i].expectFound ? g_cases[i].expectPos : -1,
               ok ? "PASS" : "FAIL");
    }

    if (failures == 0) {
        printf("\nALL %d CASES PASSED\n", i);
        return 0;
    } else {
        printf("\n%d/%d CASES FAILED\n", failures, i);
        return 1;
    }
}
