/*
 * undo_core_test.c - GENERATED by gen_undo_core_test.py. Do not edit by
 * hand; re-run the generator instead.
 *
 * Host-native (not SmallerC/PC-98) unit test for TSUBAKI.C's Undo engine.
 * is_lead_byte() through undo_perform() below are extracted verbatim from
 * TSUBAKI.C (see gen_undo_core_test.py for the exact function list), so
 * this test exercises the exact code that ships, not a hand-retyped copy.
 */
#include <stdio.h>
#include <string.h>

/* ---- constants extracted from TSUBAKI.C's #defines ------------------ */
#define TEXT_MAX    24576
#define MAX_LINES   1500
#define TAB_WIDTH   8
#define VRAM_COLS   80
#define BODY_ROWS   23
#define UNDO_BUF_SIZE    2048
#define UNDO_MASK        (UNDO_BUF_SIZE - 1)
#define UNDO_TYPE_INSERT 1
#define UNDO_TYPE_DELETE 2
#define UNDO_HDR_SIZE    5
#define UNDO_FOOTER_SIZE 2
#define UNDO_RESULT_EMPTY  0
#define UNDO_RESULT_OK     1
#define UNDO_RESULT_FAILED 2

/* ---- globals extracted from TSUBAKI.C's declarations ----------------- */
char g_text[TEXT_MAX + 1];
unsigned int g_lineStart[MAX_LINES];
int g_textLen;
int g_lineCount;
int g_curLine;
int g_curByte;
int g_goalCol;
int g_topLine;
int g_leftCol;
int g_lineOverflow;
int g_modified;
unsigned char g_undoBuf[UNDO_BUF_SIZE];
unsigned int g_undoWrite;
unsigned int g_undoUsed;
int g_undoApplying;
char g_undoTmp[UNDO_BUF_SIZE];

/* ---- Undo engine, extracted verbatim from TSUBAKI.C ------------------ */

int is_lead_byte(unsigned char c)
{
  return (c >= 0x81 && c <= 0x9F) || (c >= 0xE0 && c <= 0xFC);
}

/* g_text[0..g_textLen)全体を'\n'で分割し直し、g_lineStart[]/g_lineCountを
   再構築する。挿入・削除のたびに毎回全体を再構築する（設計書2章：
   「24KBの走査は正しさを優先して許容する」）。ファイルが'\n'で終わって
   いれば末尾に空行が1つ増える（split()と同じ挙動）。保存時にN行を
   N-1個の'\n'で連結し直すことで、この空行が元の「末尾に改行がある」
   状態を正確に復元する（save_file()参照）。
   実際の行数がMAX_LINESを超える場合、g_lineStart[]へこれ以上書き込む
   余地が無いのでMAX_LINESで打ち切るが、そのことをg_lineOverflowへ
   記録する。呼び出し元（load_file()）はこれを見て「黙って切り捨てず、
   読み込みを中止する」（設計書2章）を実行する。 */
void rebuild_lines(void)
{
  int i;
  int count;

  g_lineStart[0] = 0;
  count = 1;
  g_lineOverflow = 0;
  for (i = 0; i < g_textLen; i++) {
    if (g_text[i] == '\n') {
      if (count < MAX_LINES) {
        g_lineStart[count] = (unsigned int)(i + 1);
      } else {
        g_lineOverflow = 1;
      }
      count++;
    }
  }
  if (count > MAX_LINES) {
    g_lineOverflow = 1;
    count = MAX_LINES;
  }
  g_lineCount = count;
}

/* 行iの内容バイト数（末尾の'\n'を含まない）。次の行の開始位置から
   逆算するので、行表はオフセットだけを持てば足りる（設計書2章）。 */
int line_len(int i)
{
  if (i + 1 < g_lineCount) return (int)g_lineStart[i + 1] - 1 - (int)g_lineStart[i];
  return g_textLen - (int)g_lineStart[i];
}

/* 行lineIdxの中で、バイトオフセットbyteOffにある文字のバイト長
   （1か2）。byteOffが行の終端（改行の位置）にあるときは0を返す。 */
int char_len_at(int lineIdx, int byteOff)
{
  int start;
  int len;
  unsigned char c;

  start = (int)g_lineStart[lineIdx];
  len = line_len(lineIdx);
  if (byteOff >= len) return 0;
  c = (unsigned char)g_text[start + byteOff];
  if (is_lead_byte(c) && byteOff + 1 < len) return 2;
  return 1;
}

/* byteOffの直前の文字境界のバイトオフセット。byteOff自身が有効な
   文字境界であることが前提（呼び出し元はカーソル位置からのみ呼ぶ）。 */
int prev_char_start(int lineIdx, int byteOff)
{
  int i;
  int prev;

  i = 0;
  prev = 0;
  while (i < byteOff) {
    prev = i;
    i += char_len_at(lineIdx, i);
  }
  return prev;
}

/* 行lineIdxの先頭からbyteOffまでの表示セル数。タブは次のタブストップ
   （TAB_WIDTH桁ごと）まで進む。byteOffは文字境界であること。 */
int col_at_byte(int lineIdx, int byteOff)
{
  int start;
  int len;
  int i;
  int cellCol;
  unsigned char c;

  start = (int)g_lineStart[lineIdx];
  len = line_len(lineIdx);
  i = 0;
  cellCol = 0;
  while (i < byteOff) {
    c = (unsigned char)g_text[start + i];
    if (c == 0x09) {
      cellCol += TAB_WIDTH - (cellCol % TAB_WIDTH);
      i++;
    } else if (is_lead_byte(c) && i + 1 < len) {
      cellCol += 2;
      i += 2;
    } else {
      cellCol++;
      i++;
    }
  }
  return cellCol;
}

/* col_at_byte()の逆：targetCol以下でもっとも近い文字境界のバイト
   オフセットを返す（全角の途中には決して着地しない。設計書3章）。 */
int byte_at_col(int lineIdx, int targetCol)
{
  int start;
  int len;
  int i;
  int cellCol;
  int w;
  unsigned char c;

  start = (int)g_lineStart[lineIdx];
  len = line_len(lineIdx);
  i = 0;
  cellCol = 0;
  while (i < len) {
    c = (unsigned char)g_text[start + i];
    if (c == 0x09) {
      w = TAB_WIDTH - (cellCol % TAB_WIDTH);
    } else if (is_lead_byte(c) && i + 1 < len) {
      w = 2;
    } else {
      w = 1;
    }
    if (cellCol + w > targetCol) break;
    cellCol += w;
    if (c == 0x09) i++;
    else if (is_lead_byte(c) && i + 1 < len) i += 2;
    else i++;
  }
  return i;
}

/* g_curLine/g_curByteを有効な範囲に丸める（rebuild_lines()で行数が
   減った直後など）。 */
void clamp_cursor(void)
{
  int len;

  if (g_curLine >= g_lineCount) g_curLine = g_lineCount - 1;
  if (g_curLine < 0) g_curLine = 0;
  len = line_len(g_curLine);
  if (g_curByte > len) g_curByte = len;
  if (g_curByte < 0) g_curByte = 0;
}

/* カーソル移動・編集の後に必ず呼ぶ：カーソルを丸め、縦横スクロール
   位置（g_topLine/g_leftCol）を最小量だけ動かしてカーソルを画面内に
   収める（設計書4章）。 */
void ensure_visible(void)
{
  int cellCol;

  clamp_cursor();
  if (g_curLine < g_topLine) g_topLine = g_curLine;
  if (g_curLine >= g_topLine + BODY_ROWS) g_topLine = g_curLine - BODY_ROWS + 1;
  if (g_topLine < 0) g_topLine = 0;

  cellCol = col_at_byte(g_curLine, g_curByte);
  if (cellCol < g_leftCol) g_leftCol = cellCol;
  if (cellCol >= g_leftCol + VRAM_COLS) g_leftCol = cellCol - VRAM_COLS + 1;
  if (g_leftCol < 0) g_leftCol = 0;
}

/* 空きが足りないとき、末尾（最古）のレコードから捨てて場所を作る。
   呼び出し元はneededがUNDO_BUF_SIZE以下であることを保証すること。 */
void undo_evict_for(unsigned int needed)
{
  unsigned int tail;
  unsigned char t;
  unsigned int len;
  unsigned int recTotal;

  while (g_undoUsed > 0 && g_undoUsed + needed > UNDO_BUF_SIZE) {
    tail = (g_undoWrite - g_undoUsed) & UNDO_MASK;
    t = g_undoBuf[tail];
    len = (unsigned int)g_undoBuf[(tail + 3) & UNDO_MASK];
    len |= (unsigned int)g_undoBuf[(tail + 4) & UNDO_MASK] << 8;
    recTotal = UNDO_HDR_SIZE + UNDO_FOOTER_SIZE;
    if (t == UNDO_TYPE_DELETE) recTotal += len;
    g_undoUsed -= recTotal;
  }
}

/* type(UNDO_TYPE_INSERT/UNDO_TYPE_DELETE)・absOffset・len・（削除のときだけ）
   payload[0..len)を1レコードとしてリングへ積む。g_undoApplying中
   （Undo自身の適用中）は何もしない（g_undoApplyingのコメント参照）。
   1レコードが空のリング全体よりも大きい場合は記録をあきらめる
   （その操作だけがUndo対象から外れる。UNDO_BUF_SIZE直前のコメント
   参照）。 */
void undo_push(int type, int absOffset, int len, char *payload)
{
  unsigned int recTotal;
  unsigned int p;
  int i;

  if (g_undoApplying) return;

  recTotal = UNDO_HDR_SIZE + UNDO_FOOTER_SIZE;
  if (type == UNDO_TYPE_DELETE) recTotal += (unsigned int)len;
  if (recTotal > UNDO_BUF_SIZE) return;

  undo_evict_for(recTotal);

  p = g_undoWrite;
  g_undoBuf[p] = (unsigned char)type;
  p = (p + 1) & UNDO_MASK;
  g_undoBuf[p] = (unsigned char)(absOffset & 0xff);
  p = (p + 1) & UNDO_MASK;
  g_undoBuf[p] = (unsigned char)((absOffset >> 8) & 0xff);
  p = (p + 1) & UNDO_MASK;
  g_undoBuf[p] = (unsigned char)(len & 0xff);
  p = (p + 1) & UNDO_MASK;
  g_undoBuf[p] = (unsigned char)((len >> 8) & 0xff);
  p = (p + 1) & UNDO_MASK;
  if (type == UNDO_TYPE_DELETE) {
    for (i = 0; i < len; i++) {
      g_undoBuf[p] = (unsigned char)payload[i];
      p = (p + 1) & UNDO_MASK;
    }
  }
  g_undoBuf[p] = (unsigned char)(recTotal & 0xff);
  p = (p + 1) & UNDO_MASK;
  g_undoBuf[p] = (unsigned char)((recTotal >> 8) & 0xff);
  p = (p + 1) & UNDO_MASK;

  g_undoWrite = p;
  g_undoUsed += recTotal;
}

/* atOffsetAbsの位置にbytes[0..nBytes)を挿入する。newlineCountは挿入する
   '\n'の個数（呼び出し元が事前に数える）で、行数の上限チェックに使う。
   容量／行数どちらかの上限を超える場合は何もせず0を返す（設計書2章：
   「容量オーバーは黙って切り捨てず、編集中に上限へ達した入力は無視し、
   ステータス行へ通知する」）。 */
int buffer_insert(int atOffsetAbs, char *bytes, int nBytes, int newlineCount)
{
  if (g_textLen + nBytes > TEXT_MAX) return 0;
  if (g_lineCount + newlineCount > MAX_LINES) return 0;
  memmove(g_text + atOffsetAbs + nBytes, g_text + atOffsetAbs, (unsigned)(g_textLen - atOffsetAbs));
  memcpy(g_text + atOffsetAbs, bytes, (unsigned)nBytes);
  g_textLen += nBytes;
  rebuild_lines();
  g_modified = 1;
  /* Undoログ：この挿入の取り消しは[atOffsetAbs, atOffsetAbs+nBytes)を
     削除するだけでよいので、バイト列そのものは保存しない。 */
  undo_push(UNDO_TYPE_INSERT, atOffsetAbs, nBytes, 0);
  return 1;
}

void buffer_delete(int atOffsetAbs, int nBytes)
{
  if (nBytes <= 0) return;
  /* Undoログ：削除の取り消しには消えるバイト列そのものが要るので、
     memmove()で上書きされる前にここで記録する。 */
  undo_push(UNDO_TYPE_DELETE, atOffsetAbs, nBytes, g_text + atOffsetAbs);
  memmove(g_text + atOffsetAbs, g_text + atOffsetAbs + nBytes, (unsigned)(g_textLen - atOffsetAbs - nBytes));
  g_textLen -= nBytes;
  rebuild_lines();
  g_modified = 1;
}

/* absOffset（絶対バイト位置）が属する行と、その行内でのバイトオフセット
   を求める。呼び出し時点でg_lineStart[]/g_lineCountが最新であることが
   前提（buffer_insert()/buffer_delete()は必ずrebuild_lines()を通した
   後に戻ってくるので、undo_perform()から呼ぶ時点では常に満たされる）。
   他のバッファ走査と同様、正しさを優先して線形探索する（設計書2章と
   同じ方針）。 */
void locate_offset(int absOffset, int *outLine, int *outByte)
{
  int i;

  for (i = 0; i + 1 < g_lineCount; i++) {
    if (absOffset < (int)g_lineStart[i + 1]) break;
  }
  *outLine = i;
  *outByte = absOffset - (int)g_lineStart[i];
}

/* Undoログの先頭（もっとも新しい記録）を1件取り消す。
   戻り値はUNDO_RESULT_*（EMPTY＝戻す記録が無い、OK＝1件取り消した、
   FAILED＝容量不足で削除の取り消し・再挿入に失敗した。記録は保持され
   ポップされないので、容量を空ければ再試行できる）。
   取り消したあと、カーソルは取り消した編集の位置（戻した内容が見える
   位置）へ移動する。
   g_modifiedは0に戻さない：すべての記録を取り消しても、それが最初に
   ファイルを開いたときの内容と一致するかを判定する仕組みが無いため
   （単純さを優先した判断。README.md参照）。 */
int undo_perform(void)
{
  unsigned int p;
  unsigned int recTotal;
  unsigned int recStart;
  unsigned char type;
  unsigned int absOffset;
  unsigned int len;
  unsigned int i;
  unsigned int src;
  int line;
  int byteOff;

  if (g_undoUsed == 0) return UNDO_RESULT_EMPTY;

  /* 直前に書いたフッタ2バイト（レコード全長）を読み、そこから
     レコード先頭まで逆向きに飛ぶ。 */
  p = (g_undoWrite - UNDO_FOOTER_SIZE) & UNDO_MASK;
  recTotal = (unsigned int)g_undoBuf[p];
  recTotal |= (unsigned int)g_undoBuf[(p + 1) & UNDO_MASK] << 8;

  recStart = (g_undoWrite - recTotal) & UNDO_MASK;

  p = recStart;
  type = g_undoBuf[p];
  p = (p + 1) & UNDO_MASK;
  absOffset = (unsigned int)g_undoBuf[p];
  p = (p + 1) & UNDO_MASK;
  absOffset |= (unsigned int)g_undoBuf[p] << 8;
  p = (p + 1) & UNDO_MASK;
  len = (unsigned int)g_undoBuf[p];
  p = (p + 1) & UNDO_MASK;
  len |= (unsigned int)g_undoBuf[p] << 8;
  p = (p + 1) & UNDO_MASK;

  g_undoApplying = 1;
  if (type == UNDO_TYPE_INSERT) {
    /* 挿入の取り消し＝その範囲を削除するだけ。 */
    buffer_delete((int)absOffset, (int)len);
  } else {
    /* 削除の取り消し＝保存したバイト列を戻す。環状バッファ上では物理
       末尾をまたいでいる可能性があるので、一旦g_undoTmp[]へ直線的に
       並べ直してからbuffer_insert()へ渡す。 */
    src = p;
    for (i = 0; i < len; i++) {
      g_undoTmp[i] = (char)g_undoBuf[src];
      src = (src + 1) & UNDO_MASK;
    }
    if (!buffer_insert((int)absOffset, g_undoTmp, (int)len, 0)) {
      g_undoApplying = 0;
      return UNDO_RESULT_FAILED;
    }
  }
  g_undoApplying = 0;

  /* このレコードぶんをリングから取り除く（Undoは一度きりのスタック
     操作。Redoは作らない方針のため、取り消した記録は戻ってこない）。 */
  g_undoWrite = recStart;
  g_undoUsed -= recTotal;

  /* カーソルを取り消した編集の位置へ（戻した内容が見える位置）。 */
  locate_offset((int)absOffset, &line, &byteOff);
  g_curLine = line;
  g_curByte = byteOff;
  g_goalCol = col_at_byte(g_curLine, g_curByte);
  ensure_visible();

  return UNDO_RESULT_OK;
}

/* ---- test harness ------------------------------------------------- */

static void reset_state(void)
{
    g_textLen = 0;
    g_text[0] = 0;
    rebuild_lines();
    g_curLine = 0;
    g_curByte = 0;
    g_goalCol = 0;
    g_topLine = 0;
    g_leftCol = 0;
    g_lineOverflow = 0;
    g_modified = 0;
    g_undoWrite = 0;
    g_undoUsed = 0;
    g_undoApplying = 0;
}

static int failures = 0;

static void check(int cond, const char *label)
{
    printf("%-70s %s\n", label, cond ? "PASS" : "FAIL");
    if (!cond) failures++;
}

/* ---- case 1: insert, then undo restores the original text ------------ */
static void test_insert_then_undo(void)
{
    int ok;

    reset_state();
    strcpy(g_text, "abcdef");
    g_textLen = (int)strlen(g_text);
    rebuild_lines();

    ok = buffer_insert(3, "XYZ", 3, 0);
    check(ok, "insert: buffer_insert() succeeds");
    check(strcmp(g_text, "abcXYZdef") == 0, "insert: text after insert is 'abcXYZdef'");
    check(g_undoUsed > 0, "insert: undo log is non-empty after insert");

    ok = (undo_perform() == UNDO_RESULT_OK);
    check(ok, "insert: undo_perform() reports OK");
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "abcdef") == 0, "insert: undo restores 'abcdef'");
    check(g_undoUsed == 0, "insert: undo log is empty again after the single undo");
}

/* ---- case 2: delete (incl. a 2-byte SJIS char), then undo restores the
   deleted bytes exactly -------------------------------------------------- */
static void test_delete_then_undo_sjis(void)
{
    int ok;
    /* "a" + KANJI U+6F22 as SJIS (0x8A 0xBF, "漢") + "b" */
    char before[8];
    int beforeLen;

    reset_state();
    before[0] = 'a'; before[1] = (char)0x8A; before[2] = (char)0xBF; before[3] = 'b'; before[4] = 0;
    beforeLen = 4;
    memcpy(g_text, before, (size_t)beforeLen + 1);
    g_textLen = beforeLen;
    rebuild_lines();

    /* delete the 2-byte SJIS character at offset 1 */
    buffer_delete(1, 2);
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "ab") == 0, "delete(sjis): text after delete is 'ab'");
    check(g_undoUsed > 0, "delete(sjis): undo log is non-empty after delete");

    ok = (undo_perform() == UNDO_RESULT_OK);
    check(ok, "delete(sjis): undo_perform() reports OK");
    g_text[g_textLen] = 0;
    check(g_textLen == beforeLen && memcmp(g_text, before, (size_t)beforeLen) == 0,
          "delete(sjis): undo restores the exact deleted SJIS bytes");
}

/* ---- case 3: several edits, undo unwinds them in reverse order -------- */
static void test_multiple_edits_reverse_order(void)
{
    reset_state();
    strcpy(g_text, "");
    g_textLen = 0;
    rebuild_lines();

    buffer_insert(0, "AAA", 3, 0);   /* "AAA" */
    buffer_insert(3, "BBB", 3, 0);   /* "AAABBB" */
    buffer_delete(0, 1);             /* "AABBB" (deleted the first 'A') */

    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AABBB") == 0, "multi: state after 3 edits is 'AABBB'");

    undo_perform(); /* undoes the delete: restore the leading 'A' */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AAABBB") == 0, "multi: undo #1 (of delete) -> 'AAABBB'");

    undo_perform(); /* undoes the second insert ("BBB") */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "AAA") == 0, "multi: undo #2 (of insert BBB) -> 'AAA'");

    undo_perform(); /* undoes the first insert ("AAA") */
    g_text[g_textLen] = 0;
    check(strcmp(g_text, "") == 0, "multi: undo #3 (of insert AAA) -> ''");

    check(undo_perform() == UNDO_RESULT_EMPTY, "multi: undo #4 reports EMPTY (nothing left)");
}

/* ---- case 4: ring overflow evicts the oldest record, which then can no
   longer be undone --------------------------------------------------- */
static void test_ring_overflow_evicts_oldest(void)
{
    int i;
    int totalPushes;
    char chunk[64];
    int chunkLen;
    int recBytes;
    int capacity;

    reset_state();
    g_textLen = 0;
    g_text[0] = 0;
    rebuild_lines();

    /* Each insert of chunkLen bytes costs UNDO_HDR_SIZE+UNDO_FOOTER_SIZE
       bytes of ring space (inserts don't carry a payload). Push enough
       distinct, individually-labelled inserts to overflow UNDO_BUF_SIZE
       several times over, so the oldest ones are guaranteed evicted. */
    chunkLen = 8;
    recBytes = UNDO_HDR_SIZE + UNDO_FOOTER_SIZE;
    capacity = UNDO_BUF_SIZE / recBytes;
    totalPushes = capacity * 3; /* push 3x the ring's record capacity */

    for (i = 0; i < totalPushes; i++) {
        sprintf(chunk, "%07d;", i); /* exactly 8 bytes: 7 digits + ';' */
        buffer_insert(g_textLen, chunk, chunkLen, 0);
    }

    check(g_undoUsed <= UNDO_BUF_SIZE, "overflow: undo log never exceeds UNDO_BUF_SIZE");

    /* Each buffer_insert() appended its chunk at the then-current
       g_textLen, so g_text is chunk0+chunk1+...+chunk(totalPushes-1) in
       order. Undo pops the most-recently-pushed record first (LIFO), so
       undoing repeatedly removes chunks from the END of g_text, working
       back toward chunk0. Keep undoing until the log reports EMPTY. */
    {
        int undoneCount = 0;
        int r;
        while ((r = undo_perform()) == UNDO_RESULT_OK) {
            undoneCount++;
            if (undoneCount > totalPushes) break; /* safety valve */
        }
        check(r == UNDO_RESULT_EMPTY, "overflow: eventually reports EMPTY (ring is finite)");
        check(undoneCount > 0 && undoneCount < totalPushes,
              "overflow: undid some records, but fewer than were pushed");
        printf("    (pushed %d records of %d bytes each; ring held room for "
               "~%d; %d were actually undoable)\n",
               totalPushes, chunkLen, capacity, undoneCount);

        /* The decisive check: chunk #0 (the OLDEST edit) must still be
           sitting at the very start of g_text, unremoved - proving its
           undo record was the one discarded when the ring overflowed,
           exactly as the ring-buffer eviction policy requires (oldest
           record evicted first, not some arbitrary one). If eviction were
           broken (e.g. evicting from the wrong end, or not evicting at
           all and instead corrupting the ring), this specific assertion
           would fail even if the generic checks above happened to pass. */
        check(g_textLen >= chunkLen &&
              memcmp(g_text, "0000000;", (size_t)chunkLen) == 0,
              "overflow: chunk #0 (oldest push) remains un-undoable in g_text");
    }
}

int main(void)
{
    printf("%-70s %s\n", "case", "result");
    test_insert_then_undo();
    test_delete_then_undo_sjis();
    test_multiple_edits_reverse_order();
    test_ring_overflow_evicts_oldest();

    if (failures == 0) {
        printf("\nALL CASES PASSED\n");
        return 0;
    } else {
        printf("\n%d CASE(S) FAILED\n", failures);
        return 1;
    }
}
